version: '3.8'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - '3000:3000' # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
  # Create backend container
  backend:
    # Create backend container
    build: ./backend
    ports:
      - '8080:8080'
    container_name: backend-docker
    restart: always
    links:
      - mongodb
  # Create database container
  mongodb:
    image: mongodb:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORKD=rootpassword
    ports:
      - '5432:5432'
    volumes:
      - mongodb_data-container:/data/db
volumes:
  mongodb_data_container:
